#!/bin/bash

function command_exists () {
  type "$1" &> /dev/null ;
}

function append_zprofile {
  LINE=$1
  FILE=~/.zprofile
  touch $FILE
  grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
}

function append_direnvrc {
  LINE=$1
  FILE=~/.config/direnv/direnvrc
  touch $FILE
  grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
}

function install_nix() {
  if ! command_exists nix; then
    echo "Installing nix"
    sh <(curl -L https://nixos.org/nix/install) --daemon --yes
  fi

  grep "experimental-features = nix-command flakes" /etc/nix/nix.conf > /dev/null

  if [[ $? -ne 0 ]]; then
    echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf > /dev/null
  fi
}

function install_direnv() {
  if ! command_exists direnv; then
    curl -sfL https://direnv.net/install.sh | zsh
  fi

  append_zprofile 'eval "$(direnv hook zsh)"'
}

function install_nix_direnv() {
  source ~/.zprofile
  nix-env -f '<nixpkgs>' -iA nix-direnv
  mkdir -p ~/.config/direnv/
  append_direnvrc 'source $HOME/.nix-profile/share/nix-direnv/direnvrc'
}

install_nix
install_direnv
install_nix_direnv

echo "if any of the nix steps failed, you might need to reboot and rerun this script ..."
